version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/bash
    ports:
      - "8080:8080"
    tty: true
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: my_secret_pw
      MYSQL_DB: mystery_mate_database
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw
      MYSQL_DATABASE: mystery_mate_database
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
